# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uptimeChecker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addserver',
            old_name='published_date',
            new_name='deployed_date',
        ),
    ]
